### ISSUE TITLE
No module named 'tkinter'

### ISSUE THREAD

**Issue by feiju12138** [komomon/Komo#2]
执行`python3 Komo.py install`时报错：
```
Traceback (most recent call last):
  File "/Komo/Komo.py", line 10, in <module>
    from core.tools.finger import finger_main
  File "/Komo/core/tools/finger/finger_main.py", line 9, in <module>
    from tkinter import N
ModuleNotFoundError: No module named 'tkinter'
```

请问这个是哪里的问题？

**Comment by feiju12138** [comment]
问题解决了，因为系统中缺少依赖

``` sh
sudo apt-get install python3-tk
sudo apt install tk-dev
```
