### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by zerorzeror** [komomon/Komo#21]
windows10中文 ，python3.7.9，第一步启动安装报错
C:\Users\Administrator\Desktop\Komo>python3 Komo.py install
Traceback (most recent call last):
  File "Komo.py", line 14, in <module>
    from core.tools.emailcollect import emailcollect_main
  File "C:\Users\Administrator\Desktop\Komo\core\tools\emailcollect\emailcollect_main.py", line 144, in <module>
    @logger.catch
  File "D:\Python37\lib\site-packages\loguru\_logger.py", line 1215, in catch
    return self.catch()(exception)
  File "D:\Python37\lib\site-packages\loguru\_logger.py", line 1254, in __call__
    "not a class (tried to wrap '%s')" % function.__name__
TypeError: Invalid object decorated with 'catch()', it must be a function, not a class (tried to wrap 'manager')

**Comment by komomon** [comment]
已修复
